// Mocks generated by Mockito 5.4.4 from annotations
// in pulse_pro/test/features/home/view/widgets/home_content_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i8;

import 'package:bloc/bloc.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:pulse_pro/bloc/app_state_bloc.dart' as _i4;
import 'package:pulse_pro/repositories/exercise_repository.dart' as _i10;
import 'package:pulse_pro/repositories/user_repository.dart' as _i2;
import 'package:pulse_pro/shared/models/day_entry.dart' as _i9;
import 'package:pulse_pro/shared/models/exercise.dart' as _i11;
import 'package:pulse_pro/shared/models/workout_plan.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserRepository_0 extends _i1.SmartFake
    implements _i2.UserRepository {
  _FakeUserRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWorkoutPlan_1 extends _i1.SmartFake implements _i3.WorkoutPlan {
  _FakeWorkoutPlan_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AppStateBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppStateBloc extends _i1.Mock implements _i4.AppStateBloc {
  @override
  _i2.UserRepository get userRepository => (super.noSuchMethod(
        Invocation.getter(#userRepository),
        returnValue: _FakeUserRepository_0(
          this,
          Invocation.getter(#userRepository),
        ),
        returnValueForMissingStub: _FakeUserRepository_0(
          this,
          Invocation.getter(#userRepository),
        ),
      ) as _i2.UserRepository);

  @override
  _i4.AppStateState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i5.dummyValue<_i4.AppStateState>(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _i5.dummyValue<_i4.AppStateState>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.AppStateState);

  @override
  _i6.Stream<_i4.AppStateState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i6.Stream<_i4.AppStateState>.empty(),
        returnValueForMissingStub: _i6.Stream<_i4.AppStateState>.empty(),
      ) as _i6.Stream<_i4.AppStateState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void add(_i4.AppStateEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i4.AppStateEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i4.AppStateState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i4.AppStateEvent>(
    _i7.EventHandler<E, _i4.AppStateState>? handler, {
    _i7.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i7.Transition<_i4.AppStateEvent, _i4.AppStateState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i7.Change<_i4.AppStateState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  @override
  _i6.Future<bool> userExists(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #userExists,
          [userId],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> createUserObject({
    required String? name,
    required int? birthdate,
    required double? weight,
    required int? height,
    required String? gender,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUserObject,
          [],
          {
            #name: name,
            #birthdate: birthdate,
            #weight: weight,
            #height: height,
            #gender: gender,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<List<String>>> generateSplit({
    required String? gender,
    required int? height,
    required double? weight,
    required int? birthdate,
    required String? workoutGoal,
    required String? workoutIntensity,
    required int? maxTimesPerWeek,
    required int? timePerDay,
    required List<String>? injuries,
    required List<String>? muscleFocus,
    required String? sportOrientation,
    required String? workoutExperience,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateSplit,
          [],
          {
            #gender: gender,
            #height: height,
            #weight: weight,
            #birthdate: birthdate,
            #workoutGoal: workoutGoal,
            #workoutIntensity: workoutIntensity,
            #maxTimesPerWeek: maxTimesPerWeek,
            #timePerDay: timePerDay,
            #injuries: injuries,
            #muscleFocus: muscleFocus,
            #sportOrientation: sportOrientation,
            #workoutExperience: workoutExperience,
          },
        ),
        returnValue: _i6.Future<List<List<String>>>.value(<List<String>>[]),
        returnValueForMissingStub:
            _i6.Future<List<List<String>>>.value(<List<String>>[]),
      ) as _i6.Future<List<List<String>>>);

  @override
  _i6.Future<_i3.WorkoutPlan> generateWorkoutPlan({
    required List<List<String>>? split,
    required String? workoutGoal,
    required String? gender,
    required int? height,
    required double? weight,
    required int? birthdate,
    required String? workoutIntensity,
    required int? timePerDay,
    required List<String>? injuries,
    required List<String>? muscleFocus,
    required String? sportOrientation,
    required String? workoutExperience,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateWorkoutPlan,
          [],
          {
            #split: split,
            #workoutGoal: workoutGoal,
            #gender: gender,
            #height: height,
            #weight: weight,
            #birthdate: birthdate,
            #workoutIntensity: workoutIntensity,
            #timePerDay: timePerDay,
            #injuries: injuries,
            #muscleFocus: muscleFocus,
            #sportOrientation: sportOrientation,
            #workoutExperience: workoutExperience,
          },
        ),
        returnValue: _i6.Future<_i3.WorkoutPlan>.value(_FakeWorkoutPlan_1(
          this,
          Invocation.method(
            #generateWorkoutPlan,
            [],
            {
              #split: split,
              #workoutGoal: workoutGoal,
              #gender: gender,
              #height: height,
              #weight: weight,
              #birthdate: birthdate,
              #workoutIntensity: workoutIntensity,
              #timePerDay: timePerDay,
              #injuries: injuries,
              #muscleFocus: muscleFocus,
              #sportOrientation: sportOrientation,
              #workoutExperience: workoutExperience,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.WorkoutPlan>.value(_FakeWorkoutPlan_1(
          this,
          Invocation.method(
            #generateWorkoutPlan,
            [],
            {
              #split: split,
              #workoutGoal: workoutGoal,
              #gender: gender,
              #height: height,
              #weight: weight,
              #birthdate: birthdate,
              #workoutIntensity: workoutIntensity,
              #timePerDay: timePerDay,
              #injuries: injuries,
              #muscleFocus: muscleFocus,
              #sportOrientation: sportOrientation,
              #workoutExperience: workoutExperience,
            },
          ),
        )),
      ) as _i6.Future<_i3.WorkoutPlan>);

  @override
  _i6.Future<void> updateWorkoutPlans(
    String? userId,
    Map<String, _i3.WorkoutPlan>? workoutPlans,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWorkoutPlans,
          [
            userId,
            workoutPlans,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateCurrentWorkoutPlan(
    String? userId,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCurrentWorkoutPlan,
          [
            userId,
            id,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> addHistoryDayEntry(
    String? userId,
    _i9.HistoryDayEntry? historyDayEntry,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addHistoryDayEntry,
          [
            userId,
            historyDayEntry,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateValue(
    String? userId,
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateValue,
          [
            userId,
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [ExerciseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseRepository extends _i1.Mock
    implements _i10.ExerciseRepository {
  @override
  _i6.Future<_i11.Exercise?> getExercise(String? exerciseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExercise,
          [exerciseId],
        ),
        returnValue: _i6.Future<_i11.Exercise?>.value(),
        returnValueForMissingStub: _i6.Future<_i11.Exercise?>.value(),
      ) as _i6.Future<_i11.Exercise?>);
}
